### ISSUE TITLE
Loading WasmMemory into module

### ISSUE THREAD

**Issue by ppedziwiatr** [justjake/quickjs-emscripten#152]
Hey,

as a follow-up of https://github.com/justjake/quickjs-emscripten/issues/146 - here's code that I'm trying to run:

```
import { getQuickJS, newQuickJSWASMModule, newVariant, RELEASE_SYNC } from "quickjs-emscripten";

async function main() {
  // module 1
  const QuickJS1 = await getQuickJS();
  const vm1 = QuickJS1.newContext();
  const res1 = vm1.evalCode(`const x = 100;
  function test() {
    return x;
  };
  `);
  res1.value.dispose();

  const testRes = vm1.unwrapResult(vm1.evalCode(`test()`))
  console.log("test result:", vm1.getNumber(testRes));
  const mem1 = QuickJS1.getWasmMemory();
  vm1.dispose();

  // module 2
  const variant = newVariant(RELEASE_SYNC, {
    wasmMemory: mem1
  });
  const QuickJS2 = await newQuickJSWASMModule(variant);
  const vm2 = QuickJS2.newContext();

  // getting " 'test' is not defined" here..
  const testRes2 = vm2.unwrapResult(vm2.evalCode(`test()`))
  console.log("test result:", vm2.getNumber(testRes2));
  testRes2.dispose();
  vm2.dispose();
}

main().catch(e => console.error(e)).finally();
```

What it does - it simply creates one quickjs module, evals some code, stores the module's Wasm memory - and then a second module is create with a Wasm memory from the first one. I would expect that all the code evaluated in the first one will be available in the second - but that's not the case. The result is:

```
test result: 100
y [ReferenceError]: 'test' is not defined
    at <eval> (eval.js)
Host: QuickJSUnwrapError
    at T.unwrapResult (file:///Users/ppe/warp/warp/node_modules/quickjs-emscripten-core/dist/chunk-VABBOY7Z.mjs:4:12568)
    at main (file:///Users/ppe/warp/warp/tools/quickjs-memory.mjs:26:24) {
  cause: {
    name: 'ReferenceError',
    message: "'test' is not defined",
    stack: '    at <eval> (eval.js)\n'
  },
```

Is this expected behaviour? If so, is it possible to somehow save a state of a module and resume the evaluation later with this exact state?

**Comment by ppedziwiatr** [comment]
One more experiment:
```
  const mem1 = new WebAssembly.Memory({
    initial: 256, //*65536
    maximum: 256  //*65536
  });
  const variant1 = newVariant(RELEASE_SYNC, {
    wasmMemory: mem1
  });
  const QuickJS1 = await newQuickJSWASMModule(variant1);
  const vm1 = QuickJS1.newContext();
  const res1 = vm1.evalCode(`const x = 100;
  function test() {
    return x;
  };
  `);
  res1.value.dispose();

  const testRes = vm1.unwrapResult(vm1.evalCode(`test()`));
  console.log("test result:", vm1.getNumber(testRes));
  const mem1Output = QuickJS1.getWasmMemory();
  console.log("buffers equal?", equal(mem1.buffer, mem1Output.buffer));
  
  
  function equal(buf1, buf2) {
    if (buf1.byteLength != buf2.byteLength) return false;
    const dv1 = new Uint8Array(buf1);
    const dv2 = new Uint8Array(buf2);
    for (let i = 0; i != buf1.byteLength; i++) {
      if (dv1[i] != dv2[i]) return false;
    }
    return true;
  }
  ```
  
  - it seems the the initial buffer (`mem1` and the buffer after evaluating some JS code `mem1Output` are exactly the same - 
  I'm not sure if the `getWasmMemory()` works properly..

**Comment by justjake** [comment]
In your first example, you create two VMs. Each VM instance is independent and has its own environment, even within the same WebAssembly memory. If you run the same logic inside one We Assembly module, you will get the same result. You need to re-use the memory address of vm1 in the cloned WebAssembly module so that you are using vm1, instead of creating vm2. 

> it seems the the initial buffer (mem1 and the buffer after evaluating some JS code mem1Output are exactly the same

If I understand correctly, I think this would be expected because these two objects are the same object. I think it works similar to this:

```js
const mem1 = []
const qjs1 = { mem: mem1 }
qjs1.mem.push(‘vm1’)
_.equal(mem1, qjs1.mem) // true
mem1 === qjs1.mem // also true
```

**Comment by justjake** [comment]
You can get the memory address of various objects like QuickJSContext, QuickJSRuntime by inspecting their private internals looking for pointer types. You’ll need to use the private constructor to create clones of the objects with the same address but referencing the new WebAssembly module via existing private APIs.

**Comment by ppedziwiatr** [comment]
> You can get the memory address of various objects like QuickJSContext, QuickJSRuntime by inspecting their private internals looking for pointer types. You’ll need to use the private constructor to create clones of the objects with the same address but referencing the new WebAssembly module via existing private APIs.

hmm...this looks a bit complicated to me...any help here would appreciated, though I obviously understand that you have better things to do ;)

**Comment by ppedziwiatr** [comment]
ok, here's what I've got so far"
```
// module 1
  const mem1 = new WebAssembly.Memory({
    initial: 256, //*65536
    maximum: 256  //*65536
  });
  const variant1 = newVariant(RELEASE_SYNC, {
    wasmMemory: mem1
  });
  const QuickJS1 = await newQuickJSWASMModule(variant1);
  const vm1 = QuickJS1.newContext();
  const res1 = vm1.evalCode(`const x = 100;
  function test() {
    return x;
  };
  `);
  res1.value.dispose();
  const testRes = vm1.unwrapResult(vm1.evalCode(`test()`));
  console.log("test result:", vm1.getNumber(testRes));
  const mem1Output = QuickJS1.getWasmMemory();
  testRes.dispose();

  // module 2
  const variant2 = newVariant(RELEASE_SYNC, {
    wasmMemory: mem1Output
  });
  const QuickJS2 = await newQuickJSWASMModule(variant2);
  const runtime = QuickJS2.newRuntime();
  console.log("runtime created");
  console.log("Creating context with memory pointing to", vm1.ctx.value);
  const ctx = new Lifetime(
    vm1.ctx.value, // pointer to the memory of vm1
    undefined,
    (ctx_ptr) => {
      this.contextMap.delete(ctx_ptr);
      this.callbacks.deleteContext(ctx_ptr);
      this.ffi.QTS_FreeContext(ctx_ptr);
    }
  );
  console.log("lifetime created");
  vm1.dispose();

  // it seems to explode here...
  const vm2 = new QuickJSContext({
    module: QuickJS2,
    ctx,
    ffi: runtime.ffi,
    rt: runtime.rt,
    ownedLifetimes: [runtime],
    runtime,
    callbacks: runtime.callbacks
  });
  runtime.context = vm2;
  console.log("context created");
  ```
  
  with the output being:
  ```
  test result: 100
runtime created
Creating context with memory pointing to 5326448
lifetime created
RuntimeError: table index is out of bounds
    at wasm://wasm/001e8b7e:wasm-function[687]:0x34871
    at wasm://wasm/001e8b7e:wasm-function[955]:0x4e69c
    at c._QTS_FreeRuntime [as QTS_FreeRuntime] (file:///Users/ppe/warp/warp/node_modules/@jitl/quickjs-wasmfile-release-sync/dist/emscripten-module.mjs:26:353)
    at s.disposer (file:///Users/ppe/warp/warp/node_modules/quickjs-emscripten-core/dist/chunk-VABBOY7Z.mjs:6:1211)
    at s.dispose (file:///Users/ppe/warp/warp/node_modules/quickjs-emscripten-core/dist/chunk-VABBOY7Z.mjs:1:2414)
    at s.dispose (file:///Users/ppe/warp/warp/node_modules/quickjs-emscripten-core/dist/chunk-VABBOY7Z.mjs:4:708)
```

Not sure if I can create a completely new runtime and attach a context that points to the memory of the old context - or maybe the runtime should be also pointing to the memory of the old runtime?

**Comment by ppedziwiatr** [comment]
Another try - by passing pointer to the context in the `ContextOptions`
```
// module 1
  const mem1 = new WebAssembly.Memory({
    initial: 256, //*65536
    maximum: 256  //*65536
  });
  const variant1 = newVariant(RELEASE_SYNC, {
    wasmMemory: mem1
  });
  const QuickJS1 = await newQuickJSWASMModule(variant1);
  const vm1 = QuickJS1.newContext();
  const res1 = vm1.evalCode(`const x = 100;
  function test() {
    return x;
  };
  `);
  res1.value.dispose();
  const testRes = vm1.unwrapResult(vm1.evalCode(`test()`));
  console.log("test result:", vm1.getNumber(testRes));
  testRes.dispose();
  const vm1Ptr = vm1.ctx.value;
  vm1.dispose();
  const mem1Output = QuickJS1.getWasmMemory();

  // module 2
  const variant2 = newVariant(RELEASE_SYNC, {
    wasmMemory: mem1Output
  });
  const QuickJS2 = await newQuickJSWASMModule(variant2);
  const runtime = QuickJS2.newRuntime();
  console.log('vm1Ptr', vm1Ptr)
  const vm2 = runtime.newContext({
    contextPointer: vm1Ptr
  });
  console.log("context created");
  const testRes2 = vm2.unwrapResult(vm2.evalCode(`test()`));
  ```
  
  - but with a similar result:
  ```
  test result: 100
vm1Ptr 5326448
context created
RuntimeError: table index is out of bounds
    at wasm://wasm/001e8b7e:wasm-function[776]:0x3f33a
    at wasm://wasm/001e8b7e:wasm-function[824]:0x446b8
    at wasm://wasm/001e8b7e:wasm-function[1182]:0x5c2cb
```

**Comment by ppedziwiatr** [comment]
One last try - with creating both runtime and context from pointers:
```
// module 1
  const mem1 = new WebAssembly.Memory({
    initial: 256, //*65536
    maximum: 256  //*65536
  });
  const variant1 = newVariant(RELEASE_SYNC, {
    wasmMemory: mem1
  });
  const QuickJS1 = await newQuickJSWASMModule(variant1);
  const vm1 = QuickJS1.newContext();
  const res1 = vm1.evalCode(`const x = 100;
  function test() {
    return x;
  };
  `);
  res1.value.dispose();
  const testRes = vm1.unwrapResult(vm1.evalCode(`test()`));
  console.log("test result:", vm1.getNumber(testRes));
  testRes.dispose();
  const vm1Ptr = vm1.ctx.value;
  const rt1Ptr = vm1.rt.value;
  vm1.dispose();
  const mem1Output = QuickJS1.getWasmMemory();

  // module 2
  const variant2 = newVariant(RELEASE_SYNC, {
    wasmMemory: mem1Output
  });
  const QuickJS2 = await newQuickJSWASMModule(variant2);
  console.log("vm1Ptr", vm1Ptr);
  console.log("rt1Ptr", rt1Ptr);
  const rt = new Lifetime(rt1Ptr, undefined, (rt_ptr) => {
    this.callbacks.deleteRuntime(rt_ptr)
    this.ffi.QTS_FreeRuntime(rt_ptr)
  })
  const runtime = new QuickJSRuntime({
    module: QuickJS2.module,
    callbacks: QuickJS2.callbacks,
    ffi: QuickJS2.ffi,
    rt
  });
  console.log("runtime created");
  // applyBaseRuntimeOptions(runtime, options)

  const vm2 = runtime.newContext({
    contextPointer: vm1Ptr
  });
  console.log("context created");
  vm2.evalCode(`test()`);
  ```
  
  with output:
  ```
  test result: 100
vm1Ptr 5326448
rt1Ptr 5324520
runtime created
context created
RuntimeError: table index is out of bounds
    at wasm://wasm/001e8b7e:wasm-function[74]:0x3729
    at wasm://wasm/001e8b7e:wasm-function[539]:0x27f06
    at wasm://wasm/001e8b7e:wasm-function[953]:0x4deb5
    at wasm://wasm/001e8b7e:wasm-function[776]:0x3f33a
    at wasm://wasm/001e8b7e:wasm-function[824]:0x446b8
```

Any suggestions would be great :)

**Comment by ppedziwiatr** [comment]
> Once you do `vm1.dispose`, the memory address is `free`'d. You can't use vm1 again after it's disposed. Maybe try leaving off all the `.dispose` calls and see if that helps.

Yup, that's why I'm disposing vm1 after storing the pointer values:
```
const vm1Ptr = vm1.ctx.value;
const rt1Ptr = vm1.rt.value;
vm1.dispose();

const mem1Output = QuickJS1.getWasmMemory();

  // module 2
  const variant2 = newVariant(RELEASE_SYNC, {
    wasmMemory: mem1Output
  });
 ```
 - but I'll try to remove all `dispose` call accoring to your suggestions.
 
 What I've managed to make working so far is a second vm created from the pointer of the first vm, but within the same runtime and module:
 ```
 const mem1 = new WebAssembly.Memory({
    initial: 256, //*65536
    maximum: 512  //*65536
  });
  const variant1 = newVariant(RELEASE_SYNC, {
    wasmMemory: mem1
  });
  const QuickJS1 = await newQuickJSWASMModule(variant1);
  const runtime = QuickJS1.newRuntime();
  
  // vm1
  const vm1 = runtime.newContext();
  const res1 = vm1.evalCode(`const x = 100;
  function test() {
    return x;
  };
  `);
  res1.value.dispose();
  const testRes = vm1.unwrapResult(vm1.evalCode(`test()`));
  console.log("test result:", vm1.getNumber(testRes));
  testRes.dispose();
  const vm1Ptr = vm1.ctx.value;
  const rt1Ptr = vm1.rt.value;
  vm1.dispose();
  
  // vm2 from vm1 ptr
  const vm2 = runtime.newContext({
    contextPointer: vm1Ptr
  });
  const testRes2 = vm2.unwrapResult(vm2.evalCode(`test()`));
  console.log("test result 2:", vm2.getNumber(testRes2));
  ```
 
 I'll keep on experimenting, thanks for your suggestions!

**Comment by tim-field** [comment]
@ppedziwiatr & @justjake  Thanks for the work here, this is really impressive. 

I'm considering using this approach as we need to polyfill quick js with localization capabilities. But the polyfilling process is very slow, too slow to run per script evaluation.

So the use case is to restore a version of quickJS which has the required polyfills in place and use this to execute scripts for different end users in our system.  We apply the polyfills then save the memory per your example, on the next evaluation we restore quickJS per your example and have a pollyiflled quickjs ready to use.  It seems to work really well. 👏 

So my question is, would it be safe to share this memory restored context between users of our system? ( we want to ensure that two users are running in isolated scripting environments )  is this a sane approach ?

**Comment by tim-field** [comment]
@justjake I'm keen to use this approach as it solves the slow polyfill of Intl packages, but am worried as it relies on protected properties. 

Would love to know your take on this.

<img width="550" alt="image" src="https://github.com/user-attachments/assets/6f2d0160-851a-49bd-877d-2000e2deebba">

<img width="577" alt="image" src="https://github.com/user-attachments/assets/92423676-d46a-4ef8-81fa-8abdcaaf6f0c">

I guess I'm really after a way to clone context 🤔

**Comment by josephrocca** [comment]
So just to confirm (apologies, I'm inexperienced with this emscripten stuff): Is the summary of this thread that it's not really possible to create a "snapshot" of a module (or runtime, or context) which can e.g. be saved to disk, and later loaded?

I for some reason thought this was one of the key use cases of QuickJS, and had been designing some features of a game engine based around this.

I tried code based on ppedziwiatr's example, but got an error about an invalid function reference when trying `this.vm.evalCode("foo()")`. 

ChatGPT is telling me that I'd need to also somehow copy:

1. The "function pointer table"
2. All the internal "bookkeeping" that emscripten does

And so it basically says that it's not feasible.

**Comment by josephrocca** [comment]
Okay so it turns out that the QuickJS package/module or some part of it (e.g. emscripten) is keeping some 'global' state which changes the internal init of memory/pointers/something for each successive QuickJS module/runtime you create. So to avoid this, you can instantiate each QuickJS module/runtime in its own Web Worker, and then snapshotting works as expected.

The disadvantage of this is that it gives the QuickJS instance an async API. Unless @justjake has a solution here, then if you need a sync API you might have to wait for [ShadowRealm](https://github.com/tc39/proposal-shadowrealm), which would prevent emscripten/QuickJS from being "stateful", in the sense that it currently seems to be.

### Working Snapshot/Restore Example:

```js
async function createRuntime({ code, snapshot }) {
  if (!code && !snapshot) throw new Error('Either code or snapshot must be provided');

  const workerCode = `
  import { newQuickJSWASMModule, newVariant, RELEASE_SYNC, Lifetime, QuickJSRuntime } from "https://esm.sh/quickjs-emscripten@0.31.0";
  
  self.onmessage = async ({ data: { type, code, snapshot } }) => {
    try {
      let wasmMemory = new WebAssembly.Memory({ initial:256, maximum:2048 });
      const variant = newVariant(RELEASE_SYNC, {wasmMemory});
      const QuickJS = await newQuickJSWASMModule(variant);
      
      let runtime, vm;
      
      if (snapshot) {
        let decompressedMemoryBuffer = await new Response(new Blob([snapshot.compressedMemoryBuffer]).stream().pipeThrough(new DecompressionStream("gzip"))).arrayBuffer();
        const newMemView = new Uint8Array(wasmMemory.buffer);
        const oldMemView = new Uint8Array(decompressedMemoryBuffer);
        newMemView.set(oldMemView);
        
        // Restore runtime from pointer (not sure if the pointer stuff is even needed?)
        const rt = new Lifetime(snapshot.runtimePointer, undefined, (rt_ptr) => {
          QuickJS.callbacks.deleteRuntime(rt_ptr);
          QuickJS.ffi.QTS_FreeRuntime(rt_ptr);
        });
  
        runtime = new QuickJSRuntime({
          module: QuickJS.module,
          callbacks: QuickJS.callbacks,
          ffi: QuickJS.ffi,
          rt
        });
  
        // Restore context from pointer
        vm = runtime.newContext({
          contextPointer: snapshot.contextPointer
        });
        
      } else {
        // Create fresh runtime and context
        runtime = QuickJS.newRuntime();
        vm = runtime.newContext();
  
        // Initialize with code
        const result = vm.evalCode(\`globalThis.self=globalThis;\${code}\`);
        if (result.error) {
          const error = vm.dump(result.error);
          result.error.dispose();
          throw new Error(\`Failed to initialize VM: \${error.type} \${error.message}\`);
        }
        result.value.dispose();
      }
  
      // Send back initial state and handle future commands
      self.onmessage = async ({ data: { cmd, args } }) => {
        try {
          switch (cmd) {
            case 'eval': {
              const result = vm.evalCode(args.code);
              if (result.error) {
                const error = vm.dump(result.error);
                result.error.dispose();
                throw new Error(\`Evaluation failed: \${error.type} \${error.message}\`);
              }
              const value = vm.dump(result.value);
              result.value.dispose();
              self.postMessage({ type: 'result', value });
              break;
            }
            case 'snapshot': {
              const compressedMemoryBuffer = await new Response(new Blob([wasmMemory.buffer]).stream().pipeThrough(new CompressionStream('gzip'))).arrayBuffer();
              const snapshot = {
                compressedMemoryBuffer,
                runtimePointer: vm.rt.value,
                contextPointer: vm.ctx.value
              };
              self.postMessage({ type: 'snapshot', snapshot }, [snapshot.compressedMemoryBuffer]);
              break;
            }
            case 'dispose': {
              vm.dispose();
              runtime.dispose();
              self.close();
              break;
            }
          }
        } catch (error) {
          self.postMessage({ type: 'error', error: error.message });
        }
      };
  
      self.postMessage({ type: 'ready' });
    } catch (error) {
      self.postMessage({ type: 'error', error: error.message });
      self.close();
    }
  };
  `;

  // Create worker from blob URL
  const blob = new Blob([workerCode], { type: 'text/javascript' });
  const workerUrl = URL.createObjectURL(blob);
  const worker = new Worker(workerUrl, { type: 'module' });
  URL.revokeObjectURL(workerUrl);

  // Initialize worker
  worker.postMessage({ type: 'init', code, snapshot });

  // Wait for ready signal
  await new Promise((resolve, reject) => {
    worker.onmessage = ({ data }) => {
      if (data.type === 'ready') resolve();
      else if (data.type === 'error') reject(new Error(data.error));
    };
  });

  // Create interface
  return {
    eval: (code) => {
      return new Promise((resolve, reject) => {
        worker.onmessage = ({ data }) => {
          if (data.type === 'result') resolve(data.value);
          else if (data.type === 'error') reject(new Error(data.error));
        };
        worker.postMessage({ cmd: 'eval', args: { code } });
      });
    },

    getMemorySnapshot: () => {
      return new Promise((resolve, reject) => {
        worker.onmessage = ({ data }) => {
          if (data.type === 'snapshot') resolve(data.snapshot);
          else if (data.type === 'error') reject(new Error(data.error));
        };
        worker.postMessage({ cmd: 'snapshot' });
      });
    },

    dispose: () => {
      worker.postMessage({ cmd: 'dispose' });
    }
  };
}






////////////////////////////////////////////
//             EXAMPLE USAGE              //
////////////////////////////////////////////
const code = `
  let foo = 1;
  let obj = {a:1};
  function doStuff(n) {
    foo += n;
    obj.a++;
    obj.fn = () => 123;
    return foo > 4 ? obj : foo;
  }
`;

// Create initial runtime:
const runtime = await createRuntime({ code });
console.log(await runtime.eval("foo")); // 1
console.log("doStuff(3)", await runtime.eval("doStuff(3)")); 
console.log(await runtime.eval("foo")); // 4

// Snapshot and delete initial runtime:
const snapshot = await runtime.getMemorySnapshot();
runtime.dispose();

// Restore runtime and continue:
const restoredRuntime = await createRuntime({ snapshot });
console.log(await restoredRuntime.eval("foo")); // Should show 4
console.log("doStuff(2)", await restoredRuntime.eval("doStuff(2)"));
console.log(await restoredRuntime.eval("foo")); // Should show 6
console.log(await restoredRuntime.eval("obj.fn()")); // Should show 123
restoredRuntime.dispose();
```

**Comment by justjake** [comment]
Interesting finding with the WebWorker to get a completely fresh copy of the JavaScript environment state. I think it should be possible to overcome the issues with Emscripten global state, but it will take some investigation of Emscripten’s JS wrapper.

My recommendation to continue this work is:

1. Build this repo from source, so you have the un-bundled Emscripten wrapper code. With a DEBUG variant built from source you (and your AI assistant) can easily understand what the Emscripten wrapper is doing.
2. force commit the Emscripten wrapper code to git, in a branch. 
3. Make whatever modifications are necessary to the wrapper stuff to add a new `snapshot` method to do the whole serialization process. This should return the copy of WASM memory as Uint8Array or similar, as well as any of the JS state we need to create a clone. This doesnt need to be serializable - just enough to make an independent clone in memory. 
4. Make whatever modifications you need to create a `restore` static method to create a new Emscripten module instance from the return value of `snapshot`

I think if you can figure out those things work mechanically at the Emscripten level, we can figure out a high level interface for full serialization to disk that we can expose to quickjs-emscripten users, as well as a way to get the wrapper code changes to work with the build system somehow.
