### ISSUE TITLE
Reproducibility Issue with README Example: Async Module Loader

### ISSUE THREAD

**Issue by petrbrzek** [justjake/quickjs-emscripten#178]
Hello @justjake, normally I would send this to the Discussion, but this repo doesn't have that option. Feel free to close this if this is not the right place to ask questions.

I am trying to reproduce the README example [Async module loader](https://github.com/justjake/quickjs-emscripten?tab=readme-ov-file#async-module-loader).

When I manually download the `esm.sh/react@17` source file and save it to disk and load it in `setModuleLoader`, I get this error.

```
y [TypeError]: not a function
    at <anonymous> (data:text/javascript;base64,ZXhwb3J0IGRlZmF1bHQgT2JqZWN0LmFzc2lnbg==:150)
    at <anonymous> (data:text/javascript;base64,ZXhwb3J0IGRlZmF1bHQgT2JqZWN0LmFzc2lnbg==)
    at <anonymous> (data:text/javascript;base64,ZXhwb3J0IGRlZmF1bHQgT2JqZWN0LmFzc2lnbg==:439)
    at <anonymous> (data:text/javascript;base64,ZXhwb3J0IGRlZmF1bHQgT2JqZWN0LmFzc2lnbg==)
    at <anonymous> (data:text/javascript;base64,ZXhwb3J0IGRlZmF1bHQgT2JqZWN0LmFzc2lnbg==:473)
Host: QuickJSUnwrapError
    at u.unwrapResult (file:///Users/petrbrzek/Desktop/dev/quickjs-emscripten-testing/node_modules/quickjs-emscripten-core/dist/chunk-TEPNWHZX.mjs:4:13478)
    at file:///Users/petrbrzek/Desktop/dev/quickjs-emscripten-testing/index.mjs:43:9 {
  cause: {
    name: 'TypeError',
    message: 'not a function',
    stack: '    at <anonymous> (data:text/javascript;base64,ZXhwb3J0IGRlZmF1bHQgT2JqZWN0LmFzc2lnbg==:150)\n' +
      '    at <anonymous> (data:text/javascript;base64,ZXhwb3J0IGRlZmF1bHQgT2JqZWN0LmFzc2lnbg==)\n' +
      '    at <anonymous> (data:text/javascript;base64,ZXhwb3J0IGRlZmF1bHQgT2JqZWN0LmFzc2lnbg==:439)\n' +
      '    at <anonymous> (data:text/javascript;base64,ZXhwb3J0IGRlZmF1bHQgT2JqZWN0LmFzc2lnbg==)\n' +
      '    at <anonymous> (data:text/javascript;base64,ZXhwb3J0IGRlZmF1bHQgT2JqZWN0LmFzc2lnbg==:473)\n'
  },
```

However, when I copy the react source from this [repo](https://github.com/justjake/quickjs-emscripten/tree/00b4d09ab36e357b168528d5f5fd7b6f8a312ad5/examples/imports/cdn.esm.sh/v69/react%4017.0.2/es2015), it works fine. When I look at the output from esm.sh, it is different.

My question is: is the example from the README still reproducible, or has esm.sh changed something, and it is no longer supported?

Thank you very much.

**Comment by petrbrzek** [comment]
Just found out that `react@18` is working, but `react@17` is not, so it's probably a regression with esm.sh.
