### ISSUE TITLE
Help with async fetch call

### ISSUE THREAD

**Issue by jtewright** [justjake/quickjs-emscripten#51]
Hi justjake,

Thank you for creating this package. It's so useful.

Can I ask for your help implementing fetch within the vm please? I've been trying to follow the documentation and the examples.

Here's the sample code I'm calling on `vm.evalCode` (the value of `code` below):
```
async () => {
return await fetch('http://api.weatherapi.com/v1/current.json?key=XXXXXXXXXX&q=EC1M&aqi=no');
}();
```

And then here's how I'm implementing quickjs-emscripten:
```
async function TestCode(code) {

    const QuickJS = await getQuickJS();
    const vm = QuickJS.createVm();

    const fetchHandle = vm.newFunction('fetch', (urlHandle) => {
        const url = vm.getString(urlHandle);
        const deferred = vm.newPromise();
        fetch(url).then(result => result.json()).then(deferred.resolve);
        return deferred.handle;
    });
    vm.setProp(vm.global, 'fetch', fetchHandle);
    fetchHandle.dispose();
    
    const evalResult = vm.unwrapResult(vm.evalCode(code));
    vm.executePendingJobs()

    const error = evalResult.error;
    const value = evalResult.value;
    const results = {
        result: error ? "failed" : "success",
        error: error ? vm.dump(error) : null,
        value: error ? null : vm.dump(value)
    };

    evalResult.dispose();
    vm.dispose();

    return results;
}
```

When I run this, I get the following stack trace:

```
Assertion failed: list_empty(&rt->gc_obj_list), at: quickjs/quickjs.c,1983,JS_FreeRuntime
Assertion failed: list_empty(&rt->gc_obj_list), at: quickjs/quickjs.c,1983,JS_FreeRuntime
API error RuntimeError: abort(Assertion failed: list_empty(&rt->gc_obj_list), at: quickjs/quickjs.c,1983,JS_FreeRuntime). Build with -s ASSERTIONS=1 for more info.
    at C ({dir}/node_modules/quickjs-emscripten/dist/quickjs-emscripten-module.js:159:55)
    at a ({dir}/node_modules/quickjs-emscripten/dist/quickjs-emscripten-module.js:251:47)
    at <anonymous>:wasm-function[590]:0x2050a
    at D (<anonymous>:wasm-function[1106]:0x3c7f9)
    at QuickJSFFI.a._QTS_FreeRuntime [as QTS_FreeRuntime] ({dir}/node_modules/quickjs-emscripten/dist/quickjs-emscripten-module.js:340:82)
    at Lifetime.disposer ({dir}/node_modules/quickjs-emscripten/dist/quickjs.js:925:23)
    at Lifetime.dispose ({dir}/node_modules/quickjs-emscripten/dist/lifetime.js:131:18)
    at Scope.dispose ({dir}/node_modules/quickjs-emscripten/dist/lifetime.js:284:26)
    at QuickJSVm.dispose ({dir}/node_modules/quickjs-emscripten/dist/quickjs.js:772:21)
    at TestCode (webpack-internal:///./lib/tester.js:30:8)
Error: Lifetime not alive
    at Lifetime.assertAlive ({dir}/node_modules/quickjs-emscripten/dist/lifetime.js:137:19)
    at Lifetime.get [as value] ({dir}/node_modules/quickjs-emscripten/dist/lifetime.js:89:18)
    at {dir}/node_modules/quickjs-emscripten/dist/quickjs.js:581:49
    at Lifetime.consume ({dir}/node_modules/quickjs-emscripten/dist/lifetime.js:121:22)
    at QuickJSVm.callFunction ({dir}/node_modules/quickjs-emscripten/dist/quickjs.js:580:51)
    at QuickJSDeferredPromise.resolve ({dir}/node_modules/quickjs-emscripten/dist/quickjs.js:108:43)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Error: Lifetime not alive
    at Lifetime.assertAlive ({dir}/node_modules/quickjs-emscripten/dist/lifetime.js:137:19)
    at Lifetime.get [as value] ({dir}/node_modules/quickjs-emscripten/dist/lifetime.js:89:18)
    at {dir}/node_modules/quickjs-emscripten/dist/quickjs.js:581:49
    at Lifetime.consume ({dir}/node_modules/quickjs-emscripten/dist/lifetime.js:121:22)
    at QuickJSVm.callFunction ({dir}/node_modules/quickjs-emscripten/dist/quickjs.js:580:51)
    at QuickJSDeferredPromise.resolve ({dir}/node_modules/quickjs-emscripten/dist/quickjs.js:108:43)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error - unhandledRejection: Error: Lifetime not alive
error - uncaughtException: RuntimeError: abort(Error: Lifetime not alive). Build with -s ASSERTIONS=1 for more info.
```

As far as I understand, something isn't waiting for the promise to resolve before the vm is getting disposed (the Lifetime not alive error), but I can't work out how to prevent that from happening.

I believe this implementation is correct according to the docs, but there are example implementations which are different, e.g. defining the promise outside of the newFunction call so that you can `await deferred` later on: https://github.com/justjake/quickjs-emscripten/blob/master/ts/quickjs.test.ts#L527 I've tried doing it that way too but can't get it to work. I can get different errors, but it's not clear what's happening.

Any help would be appreciated! 

Thank you.

**Comment by jtewright** [comment]
Update: I have got this working by defining `deferred` outside the fetch function definition so that I can await `deferred.settled` later on.

```
async function TestCode(code) {

    const QuickJS = await getQuickJS();
    const vm = QuickJS.createVm();
    let deferred = undefined;

    const fetchHandle = vm.newFunction('fetch', (urlHandle) => {
        const url = vm.getString(urlHandle);
        deferred = vm.newPromise();
        fetch(url).then(result => result.json()).then(deferred.resolve);
        return deferred.handle;
    });
    vm.setProp(vm.global, 'fetch', fetchHandle);
    fetchHandle.dispose();
    
    const evalResult = vm.unwrapResult(vm.evalCode(code));
    if (deferred) {
        await deferred.settled;
    }
    vm.executePendingJobs()

    const error = evalResult.error;
    const value = evalResult.value;
    const results = {
        result: error ? "failed" : "success",
        error: error ? vm.dump(error) : null,
        value: error ? null : vm.dump(value)
    };

    if (error) { error.dispose() } else { value.dispose() };
    vm.dispose();

    return results;
}
```
